# Generated by Django 3.2.17 on 2023-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestimonialID', models.IntegerField()),
                ('ClientNames', models.CharField(max_length=255)),
                ('ClientReview', models.TextField()),
                ('LogoImage', models.ImageField(upload_to='pics')),
                ('ServiceType', models.IntegerField()),
            ],
        ),
    ]
