# Generated by Django 3.2.17 on 2023-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='ServiceType',
            field=models.CharField(max_length=255),
        ),
    ]
