# Generated by Django 3.2.17 on 2023-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galllery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventID', models.IntegerField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('InPortfolio', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='InPortfolio',
        ),
    ]
