# Generated by Django 3.2.17 on 2023-04-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0005_auto_20230418_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galllery2',
            new_name='Gallery2',
        ),
    ]
