# Generated by Django 3.2.17 on 2023-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0006_rename_galllery2_gallery2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.TextField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('ImagePosition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterVideoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.TextField()),
                ('Video', models.FileField(upload_to='videos')),
                ('VideoPosition', models.TextField()),
            ],
        ),
    ]
