# Generated by Django 4.2.7 on 2023-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0007_masterimagetable_mastervideotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Number',
            field=models.CharField(default='XXX-XXX-XXXX', max_length=20),
        ),
    ]
